sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    database: 10  # 默认为0号数据库

  wechat:
    appid: wx99c4e04b796ca643
    secret: 42014a85c384c501a98ce2ff2bee6d9d
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://2b50fafb.r18.vip.cpolar.cn/notify/paySuccess
    refundNotifyUrl: https://2b50fafb.r18.vip.cpolar.cn/notify/refundSuccess